# pyproject.toml

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AsteroidsAI"
version = "1.0.0"

dependencies = [
    "pygame==2.1.2",
	"numpy==1.22.2"
]